name: "141"

services:
  postgres:
    image: postgres:16
    environment:
      # ${ENV_VAR:-fallback}
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-db}"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - 141-net
    
networks:
  141-net:
  
volumes:
  pgdata: